### ISSUE TITLE
Sample app: failed auth user

### ISSUE THREAD

**Issue by jekuno** [dsaronin/milia#53]
I checked out your sample application. Registering and signing in as a user works fine.
However opening the profile page (the page to edit the signed in user) at http://localhost:3000/users/edit produces an error in the sample app:
Logfile: `MILIA >>>>> [failed auth user]`
Flash error: `cannot sign in as <email missing>; check email/password`

This error already occurs on opening the page (without posting the form). In my own app I get the same error as in the sample app.

Do you have any ideas on how to fix this?

**Comment by dsaronin** [comment]
Neither the "profile" page nor the users/edit action has been enabled in
the sample-milia-app. That is actually a devise action. I did not feel it
was necessary to have that working to show how to integrate milia into a
working web application. The milia tutorial and README documentation,
together with the sample-milia-app, should show sufficiently how to
integrate with devise.

Specifically:
- you will need to have a view; model this after any of the other sign-up
views in the sample
- you'll need a line added to config/application.rb so that the correct
layout template will be added (somewhere around line 20) something similar
to (but don't copy this verbatim):
Devise::RegistrationsController.layout "sign"
- the users/edit view will have to get to devise correctly (probably
nothing further is needed to do that)
- devise will have to be enabled to allow users to edit their own
information (I don't think the sample has that turned on now). Use
config/initializers/devise.rb to change that configuration.
- you'll have to make sure that the before_action in
app/controllers/application.rb applies (or not) to the user/edit function
(it's beyond the scope of milia to have to instruct you on how to do this,
but look at app/controllers/home_controller.rb to see how to do that.
:
etc, etc, etc. In other words, these are things one does to build out a
functioning application; not necessarily to use milia.

**Comment by jekuno** [comment]
Thanks for your fast answer!

When calling users/edit in the sample app the default devise form shows up correctly and works. BUT the log shows the error message ``MILIA >>>>> [failed auth user]`` and the flash shows ``cannot sign in as <email missing>; check email/password``.

Both errors come from milias method ``authenticate_tenant!``

The routes.rb of the sample app contains:
``devise_for :users, controllers: {
    registrations: "milia/registrations"
}``

This routes ``/users/edit`` to ``milia/registrations#edit``.
This controller only defines
``skip_before_action :authenticate_tenant!, :only => [:new, :create, :cancel]``

_My first question:_
Would it make sense to add ``:edit`` here i.e. change this line to:
``skip_before_action :authenticate_tenant!, :only => [:new, :create, :edit, :cancel]``
in the milia gem?

_My second question:_
Updating the user through the ``users/edit`` form showed the error messages
as written above BUT didn't stop the filter chain!
Posting the form worked and the changes got persisted i.e. you can use the
form to change the user's email address even though there are error messages.

In Rails4 filter chains can't be halted by returning false as done in the
``authenticate_tenant!()`` method (see http://guides.rubyonrails.org/action_controller_overview.html#filters)
Would it maybe be better to redirect or to raise an exception here?!

**Comment by jekuno** [comment]
Hi @dsaronin,

I dived deeper into the milia gem:
I realized that it wouldn't help to skip `authenticate_tenant!` for editing users (as suggested before)  because `current_tenant` wouldn't be set then (see milia/lib/milia/control.rb, line 114).

The reason why the milia gem shows the `[failed auth user]` error is that the authentication isn't executed at all even though it is meant to be executed.

Why this happens:
* /users/edit routes to `milia/registrations#edit`
* This triggers the before filter `authenticate_tenant!` (milia/lib/milia/control.rb, line 101)
* Then `authenticate_user!` is called (milia/lib/milia/control.rb, line 102)
* This method belongs to devise. The method is dynamically defined in devise/lib/devise/controllers/helpers.rb, line 110, as follows:
```
           def authenticate_#{mapping}!(opts={})
            opts[:scope] = :#{mapping}
            warden.authenticate!(opts) if !devise_controller? || opts.delete(:force)
          end
```
* As we can see the `warden.authenticate!(opts)` isn't executed for devise controllers
* Because milia's registration controller is a devise controller as well (`class RegistrationsController < Devise::RegistrationsController`) the user authentication is skipped here.
* This IMHO is wrong and leads to the unexpected behaviour.
* I would suggest fixing the milia gem by forcing authentication to occur. This can be achieved by changing milia/lib/milia/control.rb, line 102 from
`unless authenticate_user!` to `unless authenticate_user!(force: true)`

I'll send a pull request.

**Comment by dsaronin** [comment]
let's think about this for a moment.
1. What is the use case for registrations/edit? isn't it for a user to
change their password when not using confirmable?
2. If that's the only use case, shouldn't the user first be signed in
BEFORE changing their password?

**Comment by jekuno** [comment]
The registrations/edit page can be used to e.g.
* change the email address
* change the password
* cancel the account

You are correct that this edit page is only used for users which are already signed in.
To prevent double authentication you could change milia/lib/milia/control.rb, line 102
from `unless authenticate_user!` to 
`if (current_user.blank? && !authenticate_user!(force: true))`

What do you think?

**Comment by dsaronin** [comment]
I think I understand now; yes, I think your suggestion might be good,
except I'd prefer the boolean reversed using an unless:
  unless !current_user.blank? || authenticate_user!(force: true)

**Comment by dsaronin** [comment]
btw, have you run the unit tests against the changes you proposed? have you
added a new test to check for the error-producing condition?

**Comment by jekuno** [comment]
I changed the line to
``unless current_user.present? || authenticate_user!(force: true)``
All tests pass. I also added two new tests.

**Comment by dsaronin** [comment]
thanks! I appreciate that prior to merge requests!
